import Link from "next/link";
import { SiteHeader } from "@/components/SiteHeader";
import { HomeForm } from "@/components/HomeForm";

export default function HomePage() {
  return <><SiteHeader /><main id="top">
    <HomeForm />
    <section className="shell value-section" aria-labelledby="value-title">
      <div className="value-heading"><p className="overline">Усе в картці замовлення</p><h2 id="value-title">Домовленості видно одразу</h2><p>Після оцінки ти побачиш, що саме входить у роботу, скільки це коштує і коли буде готовий кожен етап.</p></div>
      <div className="value-grid"><article><span>01 / Умови</span><h3>Спочатку — склад і ціна</h3><p>Менеджер перегляне завдання й надішле пропозицію. Початок роботи — після твого підтвердження та перевірки передоплати.</p></article><article><span>02 / Етапи</span><h3>Зрозуміло, що готове</h3><p>Для великих завдань розіб’ємо роботу на етапи з результатом і терміном. Готові матеріали з’являться в картці.</p></article><article><span>03 / Правки</span><h3>Зауваження — в одному місці</h3><p>Надішли коментарі викладача в кабінеті. Менеджер визначить, чи це правка в межах погодженого завдання.</p></article></div>
    </section>
    <section className="process-section" id="how-it-works"><div className="shell process-inner"><div className="process-intro"><p className="overline">Як це працює</p><h2>Від опису до готових файлів</h2><p>Можна почати з кількох речень. Методичку, точний обсяг та інші деталі додаси, коли вони будуть під рукою.</p><Link className="process-link" href="/#top">Описати завдання <span aria-hidden="true">↗</span></Link></div><ol className="process-list"><li><span>01</span><div><h3>Ти залишаєш заявку</h3><p>Пишеш, що потрібно, і вказуєш бажаний термін. Опис збережеться при переході в Telegram або звичайний браузер.</p></div></li><li><span>02</span><div><h3>Ми уточнюємо і оцінюємо</h3><p>У картці з’являться склад, ціна, термін, етапи й умови правок. Якщо чогось бракує, менеджер запитає.</p></div></li><li><span>03</span><div><h3>Ти підтверджуєш умови</h3><p>Після оплати повідомляєш про неї в кабінеті. Менеджер перевіряє надходження вручну.</p></div></li><li><span>04</span><div><h3>Отримуєш результат у кабінеті</h3><p>Там видно готові етапи, файли та історію змін. Зауваження також подаються через картку.</p></div></li></ol></div></section>
    <section className="shell preview-section" aria-labelledby="preview-title"><div className="preview-copy"><p className="overline">Картка замовлення</p><h2 id="preview-title">Без пошуку файлів у переписці</h2><p>Склад, етапи, оплата і матеріали зібрані в одному місці. Картка відкривається з телефона й комп’ютера.</p><ul><li>Поточний стан і наступна дія</li><li>Погоджена версія умов</li><li>Етапи та доступні файли</li><li>Платежі, правки й історія</li></ul><Link href="/cabinet">Увійти в кабінет <span aria-hidden="true">→</span></Link></div><div className="preview-card" aria-label="Приклад структури картки замовлення"><div className="preview-card-top"><span>Здайка<span className="brand-spark" /></span><span>Приклад інтерфейсу</span></div><div className="preview-card-body"><div className="preview-card-status"><span className="status-pill">Виконуємо</span><span>Завдання</span></div><h3>Усе по замовленню — тут</h3><div className="preview-card-line"><span>Умови</span><strong>Погоджено</strong></div><div className="preview-card-line"><span>Етапи</span><strong>1 із 2 надано</strong></div><div className="preview-card-line"><span>Файли</span><strong>У картці</strong></div><div className="preview-card-footer">Це приклад екрана, не реальне замовлення.</div></div></div></section>
    <section className="shell proof-empty"><div><p className="overline">Ціни та приклади</p><h2>Оцінка після перегляду завдання</h2></div><p>Стартові ціни й приклади робіт додамо, коли будуть перевірені дані та згода клієнтів на публікацію. Зараз вартість кожної заявки визначає менеджер.</p></section>
    <section className="shell public-end"><div><p className="overline">Перед замовленням</p><h2>Правила можна прочитати заздалегідь</h2><p>Як погоджуємо умови, підтверджуємо оплату, приймаємо правки й зберігаємо файли.</p></div><div className="end-links"><Link href="/terms">Умови замовлення <span>↗</span></Link><Link href="/payment-terms">Оплата і правки <span>↗</span></Link><Link href="/privacy">Конфіденційність <span>↗</span></Link></div></section>
  </main><footer className="site-footer"><div className="shell"><Link className="brand footer-brand" href="/">Здайка<span className="brand-spark" /></Link><span>Завдання переглядає менеджер · українською</span><Link href="/cabinet">Кабінет ↗</Link></div></footer></>;
}
